/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-15 11:16:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<!-- HTML head section -->  \r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title> Home Page </title>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"x-UV-Comatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viwepoint\" content=\"width=device-width,initial-scale=1.0\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"kithmalHomepage/kithmalHomepage.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css\" />\r\n");
      out.write("\r\n");
      out.write("     <!-- header -->\r\n");
      out.write("     <header class=\"header\">\r\n");
      out.write("        <nav class=\"nav1\">\r\n");
      out.write("          <a href=\"home_page.html\"><img src=\"Homepage_images/logo.png\" alt=\"LOGO\" class=\"LOGO\"></a>\r\n");
      out.write("          <h1 class=\"appm\">AmazeMaet</h1>\r\n");
      out.write("          <div class=\"box\">\r\n");
      out.write("              <input type=\"searchbox\" placeholder=\"Search\" class=\"topsearch\">\r\n");
      out.write("    \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"fbox\">\r\n");
      out.write("          <img src=\"Homepage_images/icons8-help-50.png\" alt=\"help\" class=\"help\">\r\n");
      out.write("          <a href=\"user_pro.html\"> <img src=\"Homepage_images/icons8-user-100.png\" alt=\"user\" class=\"user\"></a>\r\n");
      out.write("          </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    \r\n");
      out.write("      <!-- Navigation  bar -->\r\n");
      out.write("      <nav calss=\"nav\">\r\n");
      out.write("          <ul>\r\n");
      out.write("              <li><a href=\"home_page.html\"><b>Home</b></a></li>\r\n");
      out.write("              <li><a href=\"\"><b>Education</b></a></li>\r\n");
      out.write("              <li><a href=\"\"><b>Business</b></a></li>\r\n");
      out.write("              <li><a href=\"\"><b>Game</b></a></li>\r\n");
      out.write("              <li><a href=\"Addproduct.jsp\" onclick=\"return customFunction()\"><b>Add Product</b></a></li>\r\n");
      out.write("              <li><a href=\"\" style=\"border-right: 0;\"><b>Health & Fitness</b></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("      </header>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- HTML body section -->\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <!-- Slider preview  -->\r\n");
      out.write("    <div class=\"container swiper mySwiper\">\r\n");
      out.write("        <div class=\"content swiper-wrapper\">\r\n");
      out.write("            <div class=\"slides swiper-slide \">\r\n");
      out.write("                <img class=\"img\" src=\"Homepage_images\\abs1.jpg\">\r\n");
      out.write("                <div class=\"img_overlay\">\r\n");
      out.write("                    <h2>Order Now Product</h2>\r\n");
      out.write("                    <p>You can donload newly updated product </p>\r\n");
      out.write("                    <p>Quickly download & try it!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"slides swiper-slide \">\r\n");
      out.write("                <img class=\"img\" src=\"Homepage_images\\up.jpeg\">\r\n");
      out.write("                <div class=\"img_overlay\">\r\n");
      out.write("                    <h2>For Business </h2>\r\n");
      out.write("                    <p>you can handle your business within</p>\r\n");
      out.write("                    <p><b style=\"color: red;\">one</b> click</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"slides swiper-slide \">\r\n");
      out.write("                <img class=\"img\" src=\"Homepage_images/tr.jpg\">\r\n");
      out.write("                <div class=\"img_overlay\">\r\n");
      out.write("                    <h2>Travel with us</h2>\r\n");
      out.write("                    <p>Do You have a Travel guide?</p>\r\n");
      out.write("                    <p>Try to travel with our travel guide </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"slides swiper-slide \">\r\n");
      out.write("                <img class=\"img\" src=\"Homepage_images\\abs.jpg\">\r\n");
      out.write("                <div class=\"img_overlay\">\r\n");
      out.write("                    <h2>Uploade your product</h2>\r\n");
      out.write("                    <p>If you are a product developer you can uploade your own product</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"slides swiper-slide \">\r\n");
      out.write("                <img class=\"img\" src=\"Homepage_images/abs3.jpg\">\r\n");
      out.write("                <div class=\"img_overlay\">\r\n");
      out.write("                    <h2>Capture beautiful moment</h2>\r\n");
      out.write("                    <p>Try new pose with Different filters</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"swiper-button-next btn\"></div>\r\n");
      out.write("        <div class=\"swiper-button-prev btn\"></div>\r\n");
      out.write("        <div class=\"swiper-pagination\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- app content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!--Home section start -->\r\n");
      out.write("\r\n");
      out.write("    <section clas=\"home\" id=\"home\">\r\n");
      out.write("        <div class=\"section-wrapper\">\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <h3>Electronics Items</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("          <p class=\"qwe\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container01\">\r\n");
      out.write("            <div class=\"card-container01\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/4.jpg\" alt=\"Speaker\">\r\n");
      out.write("                    <p>2pcs Set Speaker Luxury Women Simple Dial...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.4200</span> <span class=\"discount01\">-72%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (119)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/Headset wholesaler.jpg\" alt=\"Head phone\">\r\n");
      out.write("                    <p>20pcs/can High Elastic Hair Ring French Style...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.3890</span> <span class=\"discount01\">-50%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (114)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/images (1).jpg\" alt=\"Elacteric malti meters\">\r\n");
      out.write("                    <p>Electronic Multi meters Electromagnetic...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.500</span> <span class=\"discount01\">-67%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐ (225)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/6628c0f1a9245.jpg\" alt=\"Pen\">\r\n");
      out.write("                    <p>Autumn Winter Flannel Pen Newborn...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.2,154</span> <span class=\"discount01\">-73%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (15)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/6628c0f1a9245.jpg\" alt=\"printer\">\r\n");
      out.write("                    <p>Creative Card printer good condtion...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.4620</span> <span class=\"discount01\">-70%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐ (20)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"section-wrapper\">\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <h3>Shoes Items</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("          <p class=\"qwe\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container01\">\r\n");
      out.write("            <div class=\"card-container01\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                <a href=\"kithmalProduct1.jsp\">\r\n");
      out.write("                    <img src=\"Homepage_images/sho2.jpeg\" alt=\"Shoes\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <p>Men's Running Shoes Breathable and Anti slip Air Cushion Basketball Shoes Walking Sneakers...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.4,818</span><span class=\"discount01\">Rs. 14,224</span> <span class=\"discount01\">-67%</span>\r\n");
      out.write("                    \r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (119)</span>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/50.png\" alt=\"Shoes\">\r\n");
      out.write("                    <p>20pcs/can High Elastic Hair Ring French Style...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.3890</span> <span class=\"discount01\">-50%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (114)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/53.png\" alt=\"Shoes\">\r\n");
      out.write("                    <p>Electronic Multi meters Electromagnetic...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.500</span> <span class=\"discount01\">-67%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐ (225)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/54.png\" alt=\"Shoes\">\r\n");
      out.write("                    <p>Autumn Winter Flannel Pen Newborn...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.2,154</span> <span class=\"discount01\">-73%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (15)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/51.png\" alt=\"printer\">\r\n");
      out.write("                    <p>Creative Card printer good condtion...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.4620</span> <span class=\"discount01\">-70%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐ (20)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"section-wrapper\">\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <h3>Phones Items</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"qwe\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container01\">\r\n");
      out.write("            <div class=\"card-container01\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                <a href=\"kithmalProduct2.jsp\">\r\n");
      out.write("                    <img src=\"Homepage_images/p1.jpeg\" alt=\"Shoes\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <p>iPhone 16 Series - (256GB,512GB,1TB)...</p>\r\n");
      out.write("                    <p>iPhone 16 and iPhone 16 Plus will be available in ultramarine, teal, pink, white, and black in 128GB, 256GB, and 512GB storage capacities</p>\r\n");
      out.write("                    <span class=\"price01\">Rs. 299,999</span><span class=\"discount01\">Rs. 349,999</span> <span class=\"discount01\">-14%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (119)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/p2.jpg\" alt=\"Head phone\">\r\n");
      out.write("                    <p>20pcs/can High Elastic Hair Ring French Style...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.3890</span> <span class=\"discount01\">-50%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (114)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/p3.jpg\" alt=\"Elacteric malti meters\">\r\n");
      out.write("                    <p>Electronic Multi meters Electromagnetic...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.500</span> <span class=\"discount01\">-67%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐ (225)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/p4.jpg\" alt=\"Pen\">\r\n");
      out.write("                    <p>Autumn Winter Flannel Pen Newborn...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.2,154</span> <span class=\"discount01\">-73%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (15)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/p5.jpg\" alt=\"printer\">\r\n");
      out.write("                    <p>Creative Card printer good condtion...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.4620</span> <span class=\"discount01\">-70%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐ (20)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("               </div>  \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"section-wrapper\">\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <h3>Jewerly Items</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("       <p class=\"qwe\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container01\">\r\n");
      out.write("            <div class=\"card-container01\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/j1.jpg\" alt=\"Shoes\">\r\n");
      out.write("                    <p>2pcs Set Speaker Luxury Women Simple Dial...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.4200</span> <span class=\"discount01\">-72%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (119)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/j2.jpg\" alt=\"Head phone\">\r\n");
      out.write("                    <p>20pcs/can High Elastic Hair Ring French Style...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.3890</span> <span class=\"discount01\">-50%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (114)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/j3.jpg\" alt=\"Elacteric malti meters\">\r\n");
      out.write("                    <p>Electronic Multi meters Electromagnetic...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.500</span> <span class=\"discount01\">-67%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐ (225)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/j4.jpg\" alt=\"Pen\">\r\n");
      out.write("                    <p>Autumn Winter Flannel Pen Newborn...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.2,154</span> <span class=\"discount01\">-73%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (15)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/6628c0f1a9245.jpg\" alt=\"printer\">\r\n");
      out.write("                    <p>Creative Card printer good condtion...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.4620</span> <span class=\"discount01\">-70%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (20)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"section-wrapper\">\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <h3>Shirt Items</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"qwe\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container01\">\r\n");
      out.write("            <div class=\"card-container01\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/1.jpeg\" alt=\"Shoes\">\r\n");
      out.write("                    <p>2pcs Set Speaker Luxury Women Simple Dial...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.4200</span> <span class=\"discount01\">-72%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (119)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/28.jpg\" alt=\"Head phone\">\r\n");
      out.write("                    <p>20pcs/can High Elastic Hair Ring French Style...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.3890</span> <span class=\"discount01\">-50%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (114)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/27.jpg\" alt=\"Elacteric malti meters\">\r\n");
      out.write("                    <p>Electronic Multi meters Electromagnetic...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.500</span> <span class=\"discount01\">-67%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐ (225)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/26.jpg\" alt=\"Pen\">\r\n");
      out.write("                    <p>Autumn Winter Flannel Pen Newborn...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.2,154</span> <span class=\"discount01\">-73%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐⭐ (15)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img src=\"Homepage_images/25.jpg\" alt=\"printer\">\r\n");
      out.write("                    <p>Creative Card printer good condtion...</p>\r\n");
      out.write("                    <span class=\"price01\">Rs.4620</span> <span class=\"discount01\">-70%</span>\r\n");
      out.write("                    <span class=\"rating01\">⭐⭐⭐⭐ (20)</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("<!--Footer form fieldset-->\r\n");
      out.write("<div>\r\n");
      out.write("    <form action=\"\">\r\n");
      out.write("        <fieldset borber=\"3\" style=\"display: flex; height: 200px;\">\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <ul class=\"unorderd_list\" type=\"none\">\r\n");
      out.write("                <li><a href=\"\">Support</a></li>\r\n");
      out.write("                <li><a href=\"\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"\">Contact Us</a></li>\r\n");
      out.write("                <li><a href=\"home_page.jsp\">Home</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"socialmedia_set\">\r\n");
      out.write("                <a href=\"https://www.youtube.com/\"><img class=\"socialmedia\" src=\"Homepage_images/you.png\" alt=\"You tube\"></a>\r\n");
      out.write("                <a href=\"https://www.facebook.com/ \"><img class=\"socialmedia\" src=\"Homepage_images/fb.png\" alt=\" facebook\"></a>\r\n");
      out.write("                <a href=\"https://www.Twitter.com/\"><img class=\"socialmedia\" src=\"Homepage_images/twitter-logo-png-round-3.png\" alt=\"Twitter\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </fieldset>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--Footer-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <ul class=\"foot\" type=\"none\" >\r\n");
      out.write("            <li><a href=\"\">Developer Login</a></li>\r\n");
      out.write("            <li><a href=\"\">Term of service</a></li>\r\n");
      out.write("            <li><a href=\"privacy.html\">Privacy Policy </a></li>\r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("    \r\n");
      out.write("        <hr>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- Connect Js file -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    var swiper = new Swiper(\".mySwiper\", {\r\n");
      out.write("    slidesPerView: 1,\r\n");
      out.write("    spaceBetween: 10,\r\n");
      out.write("    slidesPerGroup: 1,\r\n");
      out.write("    loop: true,\r\n");
      out.write("    loopFillGroupWithBlank: true,\r\n");
      out.write("    pagination: {\r\n");
      out.write("        el: \".swiper-pagination\",\r\n");
      out.write("        clickable: true,\r\n");
      out.write("\r\n");
      out.write("    },\r\n");
      out.write("    autoplay: {\r\n");
      out.write("        delay: 3500,\r\n");
      out.write("        disableOnInteraction: false,\r\n");
      out.write("    },\r\n");
      out.write("    navigation: {\r\n");
      out.write("        nextEl: \".swiper-button-next\",\r\n");
      out.write("        prevEl: \".swiper-button-prev\",\r\n");
      out.write("    },\r\n");
      out.write("    effect: \"creative\",\r\n");
      out.write("    creativeEffect: {\r\n");
      out.write("        prev: {\r\n");
      out.write("            shadow: true,\r\n");
      out.write("            translate: [0, 0 - 400],\r\n");
      out.write("        },\r\n");
      out.write("        next: {\r\n");
      out.write("            translate: [\"100%\", 0, 0],\r\n");
      out.write("        },\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
