/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-16 11:40:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kithmalInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Add to Cart Details</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/kithmalCSS/kithmalInsertUpdate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"JS/new.css\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h2>Enter Add to Cart Details</h2>\r\n");
      out.write("<div class=\"slideshow-container\">\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"kithmaImages/kith4.jpeg\" style=\"width:100%\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"kithmaImages/kith5.jpeg\" style=\"width:100%\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"kithmaImages/kith1.jpeg\" style=\"width:100%\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"kithmaImages/kith2.jpeg\" style=\"width:100%\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"kithmaImages/kith3.jpeg\" style=\"width:100%\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"video-ad-container\">\r\n");
      out.write("        <video id=\"adVideo\" width=\"500px\" height=\"500px\" autoplay muted controls>\r\n");
      out.write("            <source src=\"kithmalCSS/video.mp4\" type=\"video/mp4\">\r\n");
      out.write("           \r\n");
      out.write("        </video>\r\n");
      out.write("        <button id=\"pl\" onclick=\"skipAd()\">Skip Ad</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form action=\"KithmalInsertServlet\" method=\"post\">\r\n");
      out.write("        <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("    <td>Product Name:</td>\r\n");
      out.write("    <td>\r\n");
      out.write("        <input type=\"text\" id=\"ProductName\" name=\"product_Name\" required>\r\n");
      out.write("        <span class =\"class\" id=\"ProductNameError\" style=\"color: red;\"></span> <!-- Corrected ID and placement -->\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("    <td><label for=\"category\">Category:</label></td>\r\n");
      out.write("    <td>\r\n");
      out.write("        <select id=\"category\" name=\"category\" required>\r\n");
      out.write("            <option value=\"Footwear Accessories\">Footwear Accessories</option>\r\n");
      out.write("            <option value=\"Phone Accessories\">Phone Accessories</option>\r\n");
      out.write("            <option value=\"Smart Home Accessories\">Smart Home Accessories</option>\r\n");
      out.write("            <option value=\"Audio Accessories\">Audio Accessories</option>\r\n");
      out.write("            <option value=\"Photography Accessories\">Photography Accessories</option>\r\n");
      out.write("            <option value=\"Fitness Accessories\">Fitness Accessories</option>\r\n");
      out.write("            <option value=\"Travel Accessories\">Travel Accessories</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("    <td><label for=\"color\">Color:</label></td>\r\n");
      out.write("    <td>\r\n");
      out.write("    <div id=\"color-container\">\r\n");
      out.write("        <select id=\"color\" name=\"color[]\" required>\r\n");
      out.write("            <option value=\"Black\">Black</option>\r\n");
      out.write("            <option value=\"White\">White</option>\r\n");
      out.write("            <option value=\"Brown\">Brown</option>\r\n");
      out.write("            <option value=\"Navy Blue\">Navy Blue</option>\r\n");
      out.write("            <option value=\"Grey\">Grey</option>\r\n");
      out.write("            <option value=\"Red\">Red</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"qwert\">\r\n");
      out.write("    <button type=\"button\" onclick=\"addColor()\">Add Another Color</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</td>\r\n");
      out.write("<script>\r\n");
      out.write("    function addColor() {\r\n");
      out.write("        const container = document.getElementById('color-container');\r\n");
      out.write("        const newSelect = document.createElement('select');\r\n");
      out.write("        newSelect.name = 'color[]';\r\n");
      out.write("        newSelect.required = true;\r\n");
      out.write("        newSelect.innerHTML = `\r\n");
      out.write("            <option value=\"Black\">Black</option>\r\n");
      out.write("            <option value=\"White\">White</option>\r\n");
      out.write("            <option value=\"Brown\">Brown</option>\r\n");
      out.write("            <option value=\"Navy Blue\">Navy Blue</option>\r\n");
      out.write("            <option value=\"Grey\">Grey</option>\r\n");
      out.write("            <option value=\"Red\">Red</option>\r\n");
      out.write("        `;\r\n");
      out.write("        container.appendChild(newSelect);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("    <td><label for=\"size\">Size:</label></td>\r\n");
      out.write("    <td>\r\n");
      out.write("    <div id=\"size-container\">\r\n");
      out.write("        <select id=\"size\" name=\"size[]\" required>\r\n");
      out.write("            <option value=\"39\">39</option>\r\n");
      out.write("            <option value=\"40\">40</option>\r\n");
      out.write("            <option value=\"41\">41</option>\r\n");
      out.write("            <option value=\"42\">42</option>\r\n");
      out.write("            <option value=\"43\">43</option>\r\n");
      out.write("            <option value=\"44\">44</option>\r\n");
      out.write("            <option value=\"45\">45</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"qwert\">\r\n");
      out.write("    <button type=\"button\" onclick=\"addSize()\">Add Another Size</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</td>\r\n");
      out.write("<script>\r\n");
      out.write("    function addSize() {\r\n");
      out.write("        const container = document.getElementById('size-container');\r\n");
      out.write("        const newSelect = document.createElement('select');\r\n");
      out.write("        newSelect.name = 'size[]';\r\n");
      out.write("        newSelect.required = true;\r\n");
      out.write("        newSelect.innerHTML = `\r\n");
      out.write("            <option value=\"39\">39</option>\r\n");
      out.write("            <option value=\"40\">40</option>\r\n");
      out.write("            <option value=\"41\">41</option>\r\n");
      out.write("            <option value=\"42\">42</option>\r\n");
      out.write("            <option value=\"43\">43</option>\r\n");
      out.write("            <option value=\"44\">44</option>\r\n");
      out.write("            <option value=\"45\">45</option>\r\n");
      out.write("        `;\r\n");
      out.write("        container.appendChild(newSelect);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Quantity:</td>\r\n");
      out.write("                <td><input type=\"number\" name=\"quantity\" min=\"1\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"payment_Method\">Payment Method:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select id=\"payment_Method\" name=\"payment_Method\" required>\r\n");
      out.write("                        <option value=\"Credit Card\">Credit Card</option>\r\n");
      out.write("                        <option value=\"PayPal\">PayPal</option>\r\n");
      out.write("                        <option value=\"Bank Transfer\">Bank Transfer</option>\r\n");
      out.write("                        <option value=\"Cash On Delivery\">Cash On Delivery</option>\r\n");
      out.write("                        <option value=\"Debit Card\">Debit Card</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Telephone:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"telephone\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Email:</td>\r\n");
      out.write("                <td><input type=\"email\" name=\"email\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Shipping Address:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"shipping_Address\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Date Added:</td>\r\n");
      out.write("                <td><input type=\"date\" name=\"date_Added\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Comment:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"comment\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\"><input type=\"submit\" value=\"Submit\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("    <script>\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("    let isValid = true; // Fix spelling of 'isValid'\r\n");
      out.write("    \r\n");
      out.write("    // Clear the error message\r\n");
      out.write("    document.getElementById(\"ProductNameError\").innerHTML = \"\"; // Fix method name\r\n");
      out.write("    \r\n");
      out.write("    // Get the value of the input field, not the error element\r\n");
      out.write("    const productName = document.getElementById(\"ProductName\").value; // Use the correct ID for the input field\r\n");
      out.write("\r\n");
      out.write("    // Check the length of the product name\r\n");
      out.write("    if (productName.length < 3 || productName.length > 10) { // Corrected condition for length check\r\n");
      out.write("        document.getElementById(\"ProductNameError\").innerHTML = \"Product Name must be between 3 and 10 characters.\"; // Fix spelling of 'characters'\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    return isValid;\r\n");
      out.write("}\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"JS/script.js\"></script>\r\n");
      out.write("    <script src=\"JS/new.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
