/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-13 20:50:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kithmalProduct2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Product Page</title>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/kithmalCSS/kithmalProduct2.css\">\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/kithmalheader.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("        <div class=\"product-image\">\r\n");
      out.write("        <a href=\"https://www.google.com/imgres?q=iphone%2016%20series&imgurl=https%3A%2F%2Fcf-img-a-in.tosshub.com%2Fsites%2Fvisualstory%2Fwp%2F2024%2F06%2Fimage-885.png%3Fsize%3D*%3A900&imgrefurl=https%3A%2F%2Fwww.businesstoday.in%2Fvisualstories%2Ftechnology%2Fapple-iphone-16-pro-big-changes-you-can-ios-ai-142093-07-06-2024&docid=pgOf4hqMPAseZM&tbnid=nW8AVZOpGkcV1M&vet=12ahUKEwjBsY7dlISJAxXchq8BHX83K-AQM3oECCwQAA..i&w=1601&h=900&hcb=2&ved=2ahUKEwjBsY7dlISJAxXchq8BHX83K-AQM3oECCwQAA\">\r\n");
      out.write("            <img src=\"kithmaImages/product 2/I phone Series 3.jpeg\" alt=\"I phone Series\" >\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"thumbnail-images\">\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 1.jpeg\" alt=\"I phone Series 1\">\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 7.jpeg\" alt=\"I phone Series 2\">\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 0.jpeg\" alt=\"I phone Series 3\">\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 6.jpeg\" alt=\"I phone Series 4\">\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 9.jpeg\" alt=\"I phone Series 1\">\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 10.jpeg\" alt=\"I phone Series 2\">\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 11.jpeg\" alt=\"I phone Series 3\">\r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"product-details\">\r\n");
      out.write("    <h1>iPhone 16 Series - (256GB,512GB,1TB)</h1>\r\n");
      out.write("    \r\n");
      out.write("    <h2>iPhone 16 and iPhone 16 Plus will be available in ultramarine, teal, pink, white, and black in 128GB, 256GB, and 512GB storage capacities</h2>\r\n");
      out.write("    <p class=\"price\">Rs. 299,999 <span class=\"discount\">Rs. 349,999</span> <span class=\"discount-percentage\">-14%</span></p>\r\n");
      out.write("    <p>Brand: Apple</p>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"ppp\">   \r\n");
      out.write("        <div class=\"containerr\">\r\n");
      out.write("            <h2>Product details of iPhone 16 Pro Max</h2>\r\n");
      out.write("            <div class=\"product-detailss\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><strong>Display:</strong> 6.9-inch Super Retina XDR OLED, 120Hz</li>\r\n");
      out.write("                    <li><strong>Processor:</strong> Apple A18 Bionic chip</li>\r\n");
      out.write("                    <li><strong>Camera:</strong> Triple 48MP + 12MP Ultra Wide + 12MP Telephoto</li>\r\n");
      out.write("                    <li><strong>Storage:</strong> 256GB (other options available)</li>\r\n");
      out.write("                    <li><strong>Battery Life:</strong> Up to 28 hours of video playback</li>\r\n");
      out.write("                    <li><strong>Operating System:</strong> iOS 18</li>\r\n");
      out.write("                    <li><strong>Water and Dust Resistance:</strong> IP68 rating, water-resistant up to 6 meters for 30 minutes. Designed to withstand everyday spills and dust.</li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li><strong>Charging:</strong> \r\n");
      out.write("		            <li>Supports MagSafe wireless charging up to 15W</li>\r\n");
      out.write("		            <li>Qi wireless charging up to 7.5W</li>\r\n");
      out.write("		            <li>USB-C fast charging, capable of reaching up to 50% charge in 30 minutes with a 20W or higher adapter</li>\r\n");
      out.write("					\r\n");
      out.write("		         </ul>\r\n");
      out.write("		         <ul>\r\n");
      out.write("				   <li><strong>Network:</strong> 5G enabled, Wi-Fi 6E, Bluetooth 5.3, Ultra Wideband (UWB) support</li>\r\n");
      out.write("				   <li><strong>Security:</strong> Face ID with advanced facial recognition technology, Secure Enclave</li>\r\n");
      out.write("				  \r\n");
      out.write("				   <li><strong>Other Features:</strong> \r\n");
      out.write("			         <li>Water and Dust Resistance: IP68 rated, water-resistant up to 6 meters for 30 minutes</li>\r\n");
      out.write("			         <li>Display: ProMotion technology with adaptive refresh rates up to 120Hz for smoother scrolling</li>\r\n");
      out.write("			         \r\n");
      out.write("				</ul>\r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("            <div class=\"tips\">\r\n");
      out.write("            <p><strong>Tips:</strong></p>\r\n");
      out.write("            \r\n");
      out.write("            <p>Please Carefully Select the Size before Placing the Order.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"button-container\">\r\n");
      out.write("        <button class=\"button buy-now\" onclick=\"location.href='kithmalInsert.jsp'\">Buy Now</button>\r\n");
      out.write("        <button class=\"button add-to-cart\" onclick=\"location.href='kithmalInsert.jsp'\">Add to Cart</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"extra-content\" id=\"extraContent\">\r\n");
      out.write("    \r\n");
      out.write("    			<div class=\"img1111111111\">\r\n");
      out.write("    			\r\n");
      out.write("    			<p>View More Images.</p>\r\n");
      out.write("    			<img src=\"kithmaImages/product 2/I phone Series 6.jpeg\" alt=\"I phone Series 6\" width=\"600px\" height=\"200px\">\r\n");
      out.write("    			<br>\r\n");
      out.write("    			<img src=\"kithmaImages/product 2/I phone Series 8.jpeg\" alt=\"I phone Series 5\" height=\"400px\">\r\n");
      out.write("    			<br>\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 2.jpeg\" alt=\"I phone Series 7\" width=\"500px\" height=\"400px\" >\r\n");
      out.write("                <br>\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 4.jpeg\" alt=\"I phone Series 6\">\r\n");
      out.write("                <img src=\"kithmaImages/product 2/I phone Series 5.jpeg\" alt=\"I phone Series 7\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"rating-container\">\r\n");
      out.write("        <h3>Ratings and Reviews of I PHONE 16 Series</h3>\r\n");
      out.write("        <div class=\"overall-rating\">\r\n");
      out.write("            <div class=\"score\">\r\n");
      out.write("                <span class=\"rating-number\">3.0</span><span class=\"out-of\">/5</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stars\">\r\n");
      out.write("                <span class=\"star\">&#9733;</span>\r\n");
      out.write("                <span class=\"star\">&#9733;</span>\r\n");
      out.write("                <span class=\"star\">&#9733;</span>\r\n");
      out.write("                <span class=\"star\">&#9734;</span>\r\n");
      out.write("                <span class=\"star\">&#9734;</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"rating-count\">133 Ratings</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"rating-breakdown\">\r\n");
      out.write("            <div class=\"star-row\">\r\n");
      out.write("                <span class=\"star\">&#9733;&#9733;&#9733;&#9733;&#9733;</span>\r\n");
      out.write("                <div class=\"bar\">\r\n");
      out.write("                    <div class=\"filled-bar\" style=\"width: 75%;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"count\">100</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"star-row\">\r\n");
      out.write("                <span class=\"star\">&#9733;&#9733;&#9733;&#9733;&#9734;</span>\r\n");
      out.write("                <div class=\"bar\">\r\n");
      out.write("                    <div class=\"filled-bar\" style=\"width: 15%;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"count\">18</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"star-row\">\r\n");
      out.write("                <span class=\"star\">&#9733;&#9733;&#9733;&#9734;&#9734;</span>\r\n");
      out.write("                <div class=\"bar\">\r\n");
      out.write("                    <div class=\"filled-bar\" style=\"width: 3%;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"count\">4</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"star-row\">\r\n");
      out.write("                <span class=\"star\">&#9733;&#9733;&#9734;&#9734;&#9734;</span>\r\n");
      out.write("                <div class=\"bar\">\r\n");
      out.write("                    <div class=\"filled-bar\" style=\"width: 2%;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"count\">3</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"star-row\">\r\n");
      out.write("                <span class=\"star\">&#9733;&#9734;&#9734;&#9734;&#9734;</span>\r\n");
      out.write("                <div class=\"bar\">\r\n");
      out.write("                    <div class=\"filled-bar\" style=\"width: 6%;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"count\">8</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"button-container\">\r\n");
      out.write("       			<button class=\"button add-to-cart\" onclick=\"location.href='kithmalInsert.jsp'\">Review and Comment</button>\r\n");
      out.write("    		</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div class=\"button-container\">\r\n");
      out.write("        <button class=\"view-more-btn\" onclick=\"showMore()\">View More</button>\r\n");
      out.write("        <button class=\"view-less-btn\" onclick=\"showLess()\" style=\"display: none;\">View Less</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"extraContent\" style=\"display: none;\">\r\n");
      out.write("        <!-- Your extra content goes here -->\r\n");
      out.write("        <p>This is the extra content that is revealed when you click \"View More\".\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function showMore() {\r\n");
      out.write("            const extraContent = document.getElementById('extraContent');\r\n");
      out.write("            extraContent.style.display = 'block'; // Show the hidden content\r\n");
      out.write("            extraContent.scrollIntoView({ behavior: 'smooth' }); // Scroll down to reveal the new content\r\n");
      out.write("\r\n");
      out.write("            // Hide the \"View More\" button and show the \"View Less\" button\r\n");
      out.write("            document.querySelector('.view-more-btn').style.display = 'none';\r\n");
      out.write("            document.querySelector('.view-less-btn').style.display = 'inline-block';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function showLess() {\r\n");
      out.write("            const extraContent = document.getElementById('extraContent');\r\n");
      out.write("            extraContent.style.display = 'none'; // Hide the extra content\r\n");
      out.write("\r\n");
      out.write("            // Show the \"View More\" button and hide the \"View Less\" button\r\n");
      out.write("            document.querySelector('.view-more-btn').style.display = 'inline-block';\r\n");
      out.write("            document.querySelector('.view-less-btn').style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    <p class=\"qwe\"><b>Just For You</b></p>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container01\">\r\n");
      out.write("        <div class=\"card-container01\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"kithmaImages/product x/watch.jpeg\" alt=\"Watch\">\r\n");
      out.write("                <p>2pcs Set Watch Luxury Women Simple Dial...</p>\r\n");
      out.write("                <span class=\"price01\">Rs.420</span> <span class=\"discount01\">-72%</span>\r\n");
      out.write("                <span class=\"rating01\">⭐⭐⭐⭐⭐ (119)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"kithmaImages/product x/hair-rings.jpeg\" alt=\"Hair Rings\">\r\n");
      out.write("                <p>20pcs/can High Elastic Hair Ring French Style...</p>\r\n");
      out.write("                <span class=\"price01\">Rs.389</span> <span class=\"discount01\">-50%</span>\r\n");
      out.write("                <span class=\"rating01\">⭐⭐⭐⭐⭐ (114)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"kithmaImages/product x/UltrasonicCleaner.jpeg\" alt=\"Ultrasonic Cleaner\">\r\n");
      out.write("                <p>Electronic Ultrasonic Electromagnetic...</p>\r\n");
      out.write("                <span class=\"price01\">Rs.384</span> <span class=\"discount01\">-67%</span>\r\n");
      out.write("                <span class=\"rating01\">⭐⭐⭐⭐ (225)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"kithmaImages/product x/Pajamas.jpeg\" alt=\"Pajamas\">\r\n");
      out.write("                <p>Autumn Winter Flannel Pajamas Newborn...</p>\r\n");
      out.write("                <span class=\"price01\">Rs.2,154</span> <span class=\"discount01\">-73%</span>\r\n");
      out.write("                <span class=\"rating01\">⭐⭐⭐⭐⭐ (15)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"kithmaImages/product x/WallClock.jpeg\" alt=\"Wall Clock\">\r\n");
      out.write("                <p>Creative Frameless DIY Wall Clock Wall Decal...</p>\r\n");
      out.write("                <span class=\"price01\">Rs.462</span> <span class=\"discount01\">-70%</span>\r\n");
      out.write("                <span class=\"rating01\">⭐⭐⭐⭐ (20)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <footer>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/kithmalfootersp.jsp", out, false);
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
