/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-14 09:24:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kithmalUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Update Product</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/kithmalCSS/kithmalInsertUpdate.css\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    String id = request.getParameter("id");
    String product_Name = request.getParameter("product_Name");
    String category = request.getParameter("category");
    String color = request.getParameter("color");
    String size = request.getParameter("size");
    String quantity = request.getParameter("quantity");
    String payment_Method = request.getParameter("payment_Method");
    String telephone = request.getParameter("telephone");
    String email = request.getParameter("email");
    String shipping_Address = request.getParameter("shipping_Address");
    String date_Added = request.getParameter("date_Added");
    String comment = request.getParameter("comment");

    // Basic validation for id
    if (id == null || id.trim().isEmpty()) {
        response.getWriter().println("<script>alert('Invalid ID. Please provide a valid product ID.'); window.location.href='kithmalWrong.jsp';</script>");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h2>Update Product</h2>\r\n");
      out.write("    <form action=\"KithmalUpdateServlet\" method=\"post\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"id\">ID:</label></td>\r\n");
      out.write("                <td><input type=\"text\" id=\"id\" name=\"id\" value=\"");
      out.print( id );
      out.write("\" readonly></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"product_Name\">Product Name:</label></td>\r\n");
      out.write("                <td><input type=\"text\" id=\"product_Name\" name=\"product_Name\" value=\"");
      out.print( product_Name );
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("             <td><label for=\"category\">Category:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select id=\"category\" name=\"category\" required>\r\n");
      out.write("                        <option value=\"Footwear Accessories\" ");
      out.print( "Footwear Accessories".equals(category) ? "selected" : "" );
      out.write(">Footwear Accessories</option>\r\n");
      out.write("                        <option value=\"Phone Accessories\" ");
      out.print( "Phone Accessories".equals(category) ? "selected" : "" );
      out.write(">Phone Accessories</option>\r\n");
      out.write("                        <option value=\"Smart Home Accessories\" ");
      out.print( "Smart Home Accessories".equals(category) ? "selected" : "" );
      out.write(">Smart Home Accessories</option>\r\n");
      out.write("                        <option value=\"Audio Accessories\" ");
      out.print( "Audio Accessories".equals(category) ? "selected" : "" );
      out.write(">Audio Accessories</option>\r\n");
      out.write("                        <option value=\"Photography Accessories\" ");
      out.print( "Photography Accessories".equals(category) ? "selected" : "" );
      out.write(">Photography Accessories</option>\r\n");
      out.write("						<option value=\"Fitness Accessories\" ");
      out.print( "Fitness Accessories".equals(category) ? "selected" : "" );
      out.write(">Fitness Accessories</option>\r\n");
      out.write("                        <option value=\"Travel Accessories\" ");
      out.print( "Travel Accessories".equals(category) ? "selected" : "" );
      out.write(">Travel Accessories</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("    <td><label for=\"color\">Color:</label></td>\r\n");
      out.write("    <td>\r\n");
      out.write("    <div id=\"color-container\">\r\n");
      out.write("        <select id=\"color\" name=\"color[]\" required>\r\n");
      out.write("            <option value=\"Black\">Black</option>\r\n");
      out.write("            <option value=\"White\">White</option>\r\n");
      out.write("            <option value=\"Brown\">Brown</option>\r\n");
      out.write("            <option value=\"Navy Blue\">Navy Blue</option>\r\n");
      out.write("            <option value=\"Grey\">Grey</option>\r\n");
      out.write("            <option value=\"Red\">Red</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"qwert\">\r\n");
      out.write("    <button type=\"button\" onclick=\"addColor()\">Add Another Color</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</td>\r\n");
      out.write("<script>\r\n");
      out.write("    function addColor() {\r\n");
      out.write("        const container = document.getElementById('color-container');\r\n");
      out.write("        const newSelect = document.createElement('select');\r\n");
      out.write("        newSelect.name = 'color[]';\r\n");
      out.write("        newSelect.required = true;\r\n");
      out.write("        newSelect.innerHTML = `\r\n");
      out.write("            <option value=\"Black\">Black</option>\r\n");
      out.write("            <option value=\"White\">White</option>\r\n");
      out.write("            <option value=\"Brown\">Brown</option>\r\n");
      out.write("            <option value=\"Navy Blue\">Navy Blue</option>\r\n");
      out.write("            <option value=\"Grey\">Grey</option>\r\n");
      out.write("            <option value=\"Red\">Red</option>\r\n");
      out.write("        `;\r\n");
      out.write("        container.appendChild(newSelect);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</tr>\r\n");
      out.write("    <td><label for=\"size\">Size:</label></td>\r\n");
      out.write("    <td>\r\n");
      out.write("    <div id=\"size-container\">\r\n");
      out.write("        <select id=\"size\" name=\"size[]\" required>\r\n");
      out.write("            <option value=\"39\">39</option>\r\n");
      out.write("            <option value=\"40\">40</option>\r\n");
      out.write("            <option value=\"41\">41</option>\r\n");
      out.write("            <option value=\"42\">42</option>\r\n");
      out.write("            <option value=\"43\">43</option>\r\n");
      out.write("            <option value=\"44\">44</option>\r\n");
      out.write("            <option value=\"45\">45</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"qwert\">\r\n");
      out.write("    <button type=\"button\" onclick=\"addSize()\">Add Another Size</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</td>\r\n");
      out.write("<script>\r\n");
      out.write("    function addSize() {\r\n");
      out.write("        const container = document.getElementById('size-container');\r\n");
      out.write("        const newSelect = document.createElement('select');\r\n");
      out.write("        newSelect.name = 'size[]';\r\n");
      out.write("        newSelect.required = true;\r\n");
      out.write("        newSelect.innerHTML = `\r\n");
      out.write("            <option value=\"39\">39</option>\r\n");
      out.write("            <option value=\"40\">40</option>\r\n");
      out.write("            <option value=\"41\">41</option>\r\n");
      out.write("            <option value=\"42\">42</option>\r\n");
      out.write("            <option value=\"43\">43</option>\r\n");
      out.write("            <option value=\"44\">44</option>\r\n");
      out.write("            <option value=\"45\">45</option>\r\n");
      out.write("        `;\r\n");
      out.write("        container.appendChild(newSelect);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"quantity\">Quantity:</label></td>\r\n");
      out.write("                <td><input type=\"number\" id=\"quantity\" name=\"quantity\" value=\"");
      out.print( quantity );
      out.write("\" min=\"1\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"payment_Method\">Payment Method:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select id=\"payment_Method\" name=\"payment_Method\" required>\r\n");
      out.write("                        <option value=\"Credit Card\" ");
      out.print( "Credit Card".equals(payment_Method) ? "selected" : "" );
      out.write(">Credit Card</option>\r\n");
      out.write("                        <option value=\"PayPal\" ");
      out.print( "PayPal".equals(payment_Method) ? "selected" : "" );
      out.write(">PayPal</option>\r\n");
      out.write("                        <option value=\"Bank Transfer\" ");
      out.print( "Bank Transfer".equals(payment_Method) ? "selected" : "" );
      out.write(">Bank Transfer</option>\r\n");
      out.write("                        <option value=\"Cash On Delivery\" ");
      out.print( "Cash On Delivery".equals(payment_Method) ? "selected" : "" );
      out.write(">Cash On Delivery</option>\r\n");
      out.write("                        <option value=\"Debit Card\" ");
      out.print( "Debit Card".equals(payment_Method) ? "selected" : "" );
      out.write(">Debit Card</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"telephone\">Telephone:</label></td>\r\n");
      out.write("                <td><input type=\"text\" id=\"telephone\" name=\"telephone\" value=\"");
      out.print( telephone );
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"email\">Email:</label></td>\r\n");
      out.write("                <td><input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print( email );
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"shipping_Address\">Shipping Address:</label></td>\r\n");
      out.write("                <td><input type=\"text\" id=\"shipping_Address\" name=\"shipping_Address\" value=\"");
      out.print( shipping_Address );
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"date_Added\">Date Added:</label></td>\r\n");
      out.write("                <td><input type=\"date\" id=\"date_Added\" name=\"date_Added\" value=\"");
      out.print( date_Added );
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"comment\">Comment:</label></td>\r\n");
      out.write("                <td><input type=\"text\" id=\"comment\" name=\"comment\" value=\"");
      out.print( comment );
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\"><input type=\"submit\" value=\"Submit\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
