/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-24 18:48:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kithmalheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<!-- HTML head section -->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title> Home Page </title>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"x-UV-Comatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viwepoint\" content=\"width=device-width,initial-scale=1.0\" />\r\n");
      out.write(" <style>\r\n");
      out.write("body {\r\n");
      out.write("    padding: 0%;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding-top: 5px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    background-color: rgb(248,228,204);\r\n");
      out.write("    position: relative;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav1 {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    background-color: rgba(115, 170, 241, 0.522);\r\n");
      out.write("    height: 70px;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("}\r\n");
      out.write(".LOGO{\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 55px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("    margin-top: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".appm{\r\n");
      out.write("    font-size: 48px;\r\n");
      out.write("    margin-left: 120px;\r\n");
      out.write("    margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write(".qwe{\r\n");
      out.write("	font-size:20px;\r\n");
      out.write("	text-align:center;\r\n");
      out.write("}\r\n");
      out.write(".container01 {\r\n");
      out.write("    max-width: 1200px;\r\n");
      out.write("    margin: 40px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("    \r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-container01 {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-wrap: wrap;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("    margin-left: 160px;\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    width: 180px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    flex: 1 1 180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card p {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price01 {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    color: #e60023;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".discount01 {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #888;\r\n");
      out.write("    margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rating01 {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: #ff9900;\r\n");
      out.write("    margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    width: 350px;\r\n");
      out.write("    margin-top: 18px;\r\n");
      out.write("    margin-left: 815px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    box-shadow: 0 10px 25px rgb(13, 145, 221);\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    padding-right: 10px;\r\n");
      out.write("}\r\n");
      out.write(".fbox{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    margin-top: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box:hover input {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box input {\r\n");
      out.write("    width: 0;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border: none;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    transition: 0.8s;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".help {\r\n");
      out.write("    margin-left: 5px;\r\n");
      out.write("    margin-top: 9px;\r\n");
      out.write("    height: 25px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user {\r\n");
      out.write("    padding-left: 8px;\r\n");
      out.write("    margin-top: -5px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border-radius: 40px;\r\n");
      out.write("    background-color: rgba(115, 170, 241, 0.523);\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li {\r\n");
      out.write("    \r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("    width: 700px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("   \r\n");
      out.write("    color: rgb(5, 28, 105);\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;\r\n");
      out.write("    font-weight: 900;\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a:hover {\r\n");
      out.write("    background-color: rgb(93, 137, 194);\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: rgb(5, 28, 105);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/Slider style/\r\n");
      out.write(".container {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    height: 50vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slides {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    height: 50vh;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slides::before {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 50vh;\r\n");
      out.write("    background: rgba(41, 39, 39, 0.6);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slides img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 50vh;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img_overlay {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%, -50%);\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img {\r\n");
      out.write("    transform: scale(1.5, 1.5);\r\n");
      out.write("    -webkit-animation-name: zoomin;\r\n");
      out.write("    -webkit-animation-duration: 60s;\r\n");
      out.write("    animation-name: zoomin;\r\n");
      out.write("    animation-duration: 60s;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes zoomin {\r\n");
      out.write("    from {\r\n");
      out.write("        transform: scale(1, 1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    to {\r\n");
      out.write("        transform: scale(1.5, 1.5);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes zoomin {\r\n");
      out.write("    from {\r\n");
      out.write("        transform: scale(1, 1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    to {\r\n");
      out.write("        transform: scale(1.5, 1.5);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img_overlay p {\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    color: rgb(238, 240, 235);\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    font-size: medium;\r\n");
      out.write("    font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img_overlay h2 {\r\n");
      out.write("    font-size: 3.5rem;\r\n");
      out.write("    letter-spacing: 5px;\r\n");
      out.write("    color: rgb(2, 92, 87);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn::after {\r\n");
      out.write("    color: rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-button-next {\r\n");
      out.write("    margin-right: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-button-prev {\r\n");
      out.write("    margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:900px) {\r\n");
      out.write("    .swiper-button-next {\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .swiper-button-prev {\r\n");
      out.write("        margin-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .img_overlay p {\r\n");
      out.write("        font-size: 1.5rem;\r\n");
      out.write("        color: rgb(238, 240, 235);\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: medium;\r\n");
      out.write("        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .img_overlay h2 {\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        letter-spacing: 5px;\r\n");
      out.write("        color: rgb(10, 226, 215);\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media(max-width:768px) {\r\n");
      out.write("        .swiper-button-next {\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .swiper-button-prev {\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .img_overlay p {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: rgb(238, 240, 235);\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: medium;\r\n");
      out.write("            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .img_overlay h2 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            letter-spacing: 5px;\r\n");
      out.write("            color: rgb(10, 226, 215);\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:768px) {\r\n");
      out.write("    .swiper-button-next {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .swiper-button-prev {\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .img_overlay p {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        color: rgb(238, 240, 235);\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: medium;\r\n");
      out.write("        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .img_overlay h2 {\r\n");
      out.write("        font-size: 1.5rem;\r\n");
      out.write("        letter-spacing: 5px;\r\n");
      out.write("        color: rgb(10, 226, 215);\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/content style/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("h3{\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("    margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write(".content{\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write(".section-wrapper{\r\n");
      out.write("    clear: both;\r\n");
      out.write("}\r\n");
      out.write(".image{\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-left: 250px;\r\n");
      out.write("    margin-right: -20px;\r\n");
      out.write("    margin-bottom: 50px;\r\n");
      out.write("}\r\n");
      out.write(".Image1{\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".details{\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    line-height: 5px;\r\n");
      out.write("    margin-left: 150px;\r\n");
      out.write("    margin-top: -100px;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".box1{\r\n");
      out.write("   \r\n");
      out.write("   padding-left: 15px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/fealid set/\r\n");
      out.write(".unorderd_list{\r\n");
      out.write("    margin-left: 900px;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: medium;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    margin-right: 300px;\r\n");
      out.write("    line-height: 2.5;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: #f5f2f2;\r\n");
      out.write("}\r\n");
      out.write(".unorderd_list a{\r\n");
      out.write("    color: #f5f2f2;\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".unorderd_list a:hover{\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("    color: blueviolet;\r\n");
      out.write("}\r\n");
      out.write(".socialmedia{ \r\n");
      out.write("    width: 30px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    float: right;\r\n");
      out.write("    margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".socialmedia_set{\r\n");
      out.write("    margin-left: 950px;\r\n");
      out.write("    margin-top: 170px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("}\r\n");
      out.write("fieldset{\r\n");
      out.write("    \r\n");
      out.write("    border-color: #000000;\r\n");
      out.write("   background-color: #000000;\r\n");
      out.write("    margin: 10px 20p 10px 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("/* feldset style end*/\r\n");
      out.write("\r\n");
      out.write("/footer style/\r\n");
      out.write(".foot{\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".foot li{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-left: 200px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    display: inline;\r\n");
      out.write("    font-size: small;  \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/footer style end/\r\n");
      out.write("\r\n");
      out.write(" </style>   \r\n");
      out.write("   \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- HTML body section -->\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("    <head>\r\n");
      out.write("        <title> Home Page </title>\r\n");
      out.write("        <meta charset=\"UTF-8\" />\r\n");
      out.write("        <meta http-equiv=\"x-UV-Comatible\" content=\"IE=edge\" />\r\n");
      out.write("        <meta name=\"viwepoint\" content=\"width=device-width,initial-scale=1.0\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/Homepage.css\">\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("         <!-- header -->\r\n");
      out.write("         <header class=\"header\">\r\n");
      out.write("            <nav class=\"nav1\">\r\n");
      out.write("              <a href=\"home_page.jsp\"><img src=\"kithmaImages/kithmalheader/kithmalweblogo.jpg\" alt=\"LOGO\" class=\"LOGO\"></a>\r\n");
      out.write("              <h1 class=\"appm\">AmazeMaet</h1>\r\n");
      out.write("              <div class=\"box\">\r\n");
      out.write("                  <input type=\"searchbox\" placeholder=\"Search\" class=\"topsearch\">\r\n");
      out.write("        \r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"fbox\">\r\n");
      out.write("              <img src=\"kithmaImages/kithmalheader/kithmalq.jpg\" alt=\"help\" class=\"help\">\r\n");
      out.write("              <a href=\"user_pro.html\"> <img src=\"kithmaImages/kithmalheader/kithmallogo.jpg\" alt=\"user\" class=\"user\"></a>\r\n");
      out.write("              </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("        \r\n");
      out.write("          <!-- Navigation  bar -->\r\n");
      out.write("          <nav calss=\"nav\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                  <li><a href=\"home_page.jsp\"><b>Home</b></a></li>\r\n");
      out.write("                  <li><a href=\"\"><b>Education</b></a></li>\r\n");
      out.write("                  <li><a href=\"\"><b>Business</b></a></li>\r\n");
      out.write("                  <li><a href=\"\"><b>Game</b></a></li>\r\n");
      out.write("                  <li><a href=\"\" ><b>Add Product</b></a></li>\r\n");
      out.write("                  <li><a href=\"\"><b>Health & Fitness</b></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </nav>\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("          </header>\r\n");
      out.write("\r\n");
      out.write("      </body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
