/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-15 19:15:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kithmalfootersp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Health & Fitness</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Basic reset */\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer styling */\r\n");
      out.write("        footer {\r\n");
      out.write("            background: linear-gradient(to right, #333, #444);\r\n");
      out.write("            color: #f5f5f5;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            box-shadow: 0 -5px 15px rgba(0, 0, 0, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-content {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-links, .footer-social-media, .footer-language, .footer-newsletter {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer Links */\r\n");
      out.write("        .footer-links ul {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            \r\n");
      out.write("            margin-left:28%;\r\n");
      out.write("           margin-right:50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-links ul li {\r\n");
      out.write("            margin: 8px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-links ul li a, .footer-links ul li button {\r\n");
      out.write("            color: #f5f5f5;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("           \r\n");
      out.write("            transition: background-color 0.3s, color 0.3s;\r\n");
      out.write("            background-color: #555;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-links ul li a:hover, .footer-links ul li button:hover {\r\n");
      out.write("            background-color: #ff6347;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("           \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Social Media Icons */\r\n");
      out.write("        .footer-social-media img {\r\n");
      out.write("            width: 35px;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-social-media img:hover {\r\n");
      out.write("            transform: scale(1.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Language Selector */\r\n");
      out.write("        .footer-language select {\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            background-color: #555;\r\n");
      out.write("            color: #f5f5f5;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-language select:hover {\r\n");
      out.write("            background-color: #ff6347;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Newsletter */\r\n");
      out.write("        .footer-newsletter h3 {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-newsletter input[type=\"email\"] {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-newsletter button {\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            background-color: #ff6347;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-newsletter button:hover {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .footer-content {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .footer-links ul {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                gap: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .footer-newsletter input[type=\"email\"] {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                margin: 10px 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .socialmedia, .lng {\r\n");
      out.write("    width: 35px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("        <!-- Language Selector -->\r\n");
      out.write("        <div class=\"footer-language\">\r\n");
      out.write("            <img src=\"kithmaImages/footer/kithmalword.jpg\" alt=\"Language Icon\" class=\"lng\">\r\n");
      out.write("            <select name=\"lan\" id=\"lan\">\r\n");
      out.write("                <option value=\"Eng\">English</option>\r\n");
      out.write("                <option value=\"Sin\">Sinhala</option>\r\n");
      out.write("                <option value=\"Kor\">Korean</option>\r\n");
      out.write("                <option value=\"Chn\">Chinese</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Newsletter Subscription -->\r\n");
      out.write("        <div class=\"footer-newsletter\">\r\n");
      out.write("            <h3>Subscribe to our Newsletter</h3>\r\n");
      out.write("            <input type=\"email\" placeholder=\"Enter your email address\">\r\n");
      out.write("            <button type=\"submit\">Subscribe</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
