/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-14 09:47:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Review_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Review and Rating Form</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"review.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .error {\r\n");
      out.write("            color: red;\r\n");
      out.write("            font-size: 0.9em;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <form id=\"reviewForm\" action=\"Addreview\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("        <h2>Product Review Form</h2>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"product-id\">Product ID:</label>\r\n");
      out.write("        <input type=\"text\" id=\"product-id\" name=\"product_id\" required minlength=\"5\" maxlength=\"10\">\r\n");
      out.write("        <span class=\"error\" id=\"productIdError\"></span>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"user-id\">User ID:</label>\r\n");
      out.write("        <input type=\"text\" id=\"user-id\" name=\"user_id\" required minlength=\"5\" maxlength=\"10\">\r\n");
      out.write("        <span class=\"error\" id=\"userIdError\"></span>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"review-text\">Review:</label>\r\n");
      out.write("        <textarea id=\"review-text\" name=\"review_text\" rows=\"4\" required minlength=\"10\"></textarea>\r\n");
      out.write("        <span class=\"error\" id=\"reviewTextError\"></span>\r\n");
      out.write("\r\n");
      out.write("        <label>Rating:</label>\r\n");
      out.write("        <div class=\"rating-checkbox\" id=\"ratingCheckboxes\">\r\n");
      out.write("            <label><input type=\"checkbox\" name=\"rating\" value=\"5\"> Excellent</label>\r\n");
      out.write("            <label><input type=\"checkbox\" name=\"rating\" value=\"4\"> Very Good</label>\r\n");
      out.write("            <label><input type=\"checkbox\" name=\"rating\" value=\"3\"> Good</label>\r\n");
      out.write("            <label><input type=\"checkbox\" name=\"rating\" value=\"2\"> Fair</label>\r\n");
      out.write("            <label><input type=\"checkbox\" name=\"rating\" value=\"1\"> Poor</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <span class=\"error\" id=\"ratingError\"></span>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\">Submit Review</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function validateForm() {\r\n");
      out.write("            let isValid = true;\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById(\"productIdError\").innerHTML = \"\";\r\n");
      out.write("            document.getElementById(\"userIdError\").innerHTML = \"\";\r\n");
      out.write("            document.getElementById(\"reviewTextError\").innerHTML = \"\";\r\n");
      out.write("            document.getElementById(\"ratingError\").innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("            const productId = document.getElementById(\"product-id\").value;\r\n");
      out.write("            if (productId.length < 5 || productId.length > 10) {\r\n");
      out.write("                document.getElementById(\"productIdError\").innerHTML = \"Product ID must be between 5 and 10 characters.\";\r\n");
      out.write("                isValid = false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            const userId = document.getElementById(\"user-id\").value;\r\n");
      out.write("            if (userId.length < 5 || userId.length > 10) {\r\n");
      out.write("                document.getElementById(\"userIdError\").innerHTML = \"User ID must be between 5 and 10 characters.\";\r\n");
      out.write("                isValid = false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            const reviewText = document.getElementById(\"review-text\").value;\r\n");
      out.write("            if (reviewText.length < 10) {\r\n");
      out.write("                document.getElementById(\"reviewTextError\").innerHTML = \"Review text must be at least 10 characters long.\";\r\n");
      out.write("                isValid = false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            const ratingCheckboxes = document.querySelectorAll('input[name=\"rating\"]:checked');\r\n");
      out.write("            if (ratingCheckboxes.length === 0) {\r\n");
      out.write("                document.getElementById(\"ratingError\").innerHTML = \"Please select a rating.\";\r\n");
      out.write("                isValid = false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            return isValid;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
